// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Victor França

/**
 * Bundle the Camunda Modeler client plugin into a self-contained, drop-in
 * plugin directory at `dist/plugin/`:
 *
 *   dist/plugin/
 *     index.js        — the plugin entry the Modeler discovers (plugins/<name>/index.js);
 *                       a CommonJS module pointing at the renderer script + style
 *     client.js       — the bundled renderer entry (client/index.jsx)
 *     style.css       — the overlay layout stylesheet
 *     package.json    — plugin metadata (name/version/license)
 *
 * Copy (or symlink) `dist/plugin/` into the Modeler's plugins directory to
 * install. See README.md.
 *
 * Prerequisite: `tsc -b` has produced `dist/index.js` (the library this entry
 * imports). The `build:plugin` npm script chains both.
 */

import { build } from "esbuild";
import { mkdir, writeFile, copyFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const pkgDir = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(pkgDir, "dist", "plugin");

// `camunda-modeler-plugin-helpers` MUST be bundled in, not externalized: its
// `/react` and `/components` entries are thin shims that read host globals at
// runtime (`window.react`, `window.components`), and `index.js` reads the
// Modeler's component registry. The renderer has no module resolver for bare
// specifiers, so leaving them external makes the bundle throw on load (the
// plugin then registers via index.js but its UI never mounts — no button).
const external = [];

await mkdir(outDir, { recursive: true });

await build({
  entryPoints: [join(pkgDir, "client", "index.jsx")],
  outfile: join(outDir, "client.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  // Classic JSX against the host's React (imported as `React` in the entry).
  jsx: "transform",
  jsxFactory: "React.createElement",
  jsxFragment: "React.Fragment",
  loader: { ".js": "jsx" },
  external,
  logLevel: "info",
});

// The plugin ENTRY the Modeler discovers: it scans for `plugins/<name>/index.js`
// and loads this file in the MAIN (Node) process. For a renderer/client plugin
// it must export the relative paths to the bundled client script and stylesheet
// (NOT import the browser bundle). The Modeler then injects `script`/`style`
// into the renderer, where client.js calls registerClientPlugin/registerBpmnJSPlugin.
const indexJs = `// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Victor França
// Generated by scripts/build-plugin.mjs — do not edit.
module.exports = {
  name: "DPG Governance",
  style: "./style.css",
  script: "./client.js",
};
`;
await writeFile(join(outDir, "index.js"), indexJs, "utf8");

// Plugin metadata. Not used for discovery (that is index.js); kept for tooling
// and so the directory is a well-formed package.
const libPkg = JSON.parse(await readFile(join(pkgDir, "package.json"), "utf8"));
const manifest = {
  name: "dpg-governance",
  version: libPkg.version,
  description: "DPG Governance — Deterministic Process Governance panels for the Camunda Modeler.",
  license: libPkg.license ?? "Apache-2.0",
  main: "index.js",
};
await writeFile(join(outDir, "package.json"), JSON.stringify(manifest, null, 2) + "\n", "utf8");

await copyFile(join(pkgDir, "client", "style.css"), join(outDir, "style.css"));

console.log(`\n✔ Drop-in Camunda Modeler plugin written to ${outDir}`);
